"""HTTP routes for the conversation engine.

Phase 2 surface:
  POST /api/conversations            -> create a new conversation
  GET  /api/conversations/{id}       -> read transcript + status
  POST /api/conversations/{id}/turn  -> SSE stream of agent reply tokens
  POST /api/conversations/{id}/end   -> mark conversation ended
"""

from __future__ import annotations

import asyncio
import json
import logging
from collections.abc import AsyncIterator

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from sse_starlette.sse import EventSourceResponse


from app.agent.conversation import (
    Conversation,
    get_store,
    stream_user_turn,
)
from app.scoring.handoff import build_handoff
from app.scoring.schemas import HandoffRecord
from app.agent.locks import conversation_lock
from app.agent.settings import AgentSettings

log = logging.getLogger("rupeezy.agent.routes")

router = APIRouter(prefix="/api/conversations", tags=["agent"])


# ---------- DTOs ----------


class CreateConversationRequest(BaseModel):
    """Optional body for POST /api/conversations.

    When `lead_id` is present, the engine binds the conversation to that lead
    and the system-prompt builder pulls cross-call memory from prior completed
    calls of the same lead (Phase 10).
    """

    lead_id: str | None = None
    settings: AgentSettings = Field(default_factory=AgentSettings)


class CreateConversationResponse(BaseModel):
    conv_id: str
    started_at: str
    lead_id: str | None = None


class TurnRequest(BaseModel):
    text: str = Field(..., min_length=1, max_length=4000)
    # Optional language hint from the frontend voice/chat picker. When set,
    # tells the agent to reply in this language regardless of what the
    # user's text is in. Critical for romanised regional words ("Bhalobashi"
    # could be Bengali or just Latin gibberish — the picker disambiguates).
    # Accepts BCP-47 codes ("bn-IN", "en-IN") or short keys ("bengali",
    # "english"). Empty / unrecognised falls through to language detection.
    lang: str | None = Field(default=None, max_length=20)


class OpenerRequest(BaseModel):
    lang: str | None = Field(default=None, max_length=20)


class EndRequest(BaseModel):
    ended_by: str = Field(default="agent", pattern="^(agent|lead|dropped)$")


class MessageDTO(BaseModel):
    role: str
    text: str
    created_at: str


class ConversationDTO(BaseModel):
    conv_id: str
    started_at: str
    ended_at: str | None
    ended_by: str | None
    language: str
    messages: list[MessageDTO]


def _to_dto(conv: Conversation) -> ConversationDTO:
    return ConversationDTO(
        conv_id=conv.conv_id,
        started_at=conv.started_at,
        ended_at=conv.ended_at,
        ended_by=conv.ended_by,
        language=conv.language,
        messages=[MessageDTO(role=m.role, text=m.text, created_at=m.created_at) for m in conv.messages],
    )


def _row_to_dto(row) -> ConversationDTO:  # type: ignore[no-untyped-def]
    """Convert a SQLAlchemy ConversationRow to the wire DTO."""
    return ConversationDTO(
        conv_id=row.id,
        started_at=row.started_at.isoformat() if row.started_at else "",
        ended_at=row.ended_at.isoformat() if row.ended_at else None,
        ended_by=row.ended_by,
        language=row.language_used,
        messages=[
            MessageDTO(
                role=m.role,
                text=m.text,
                created_at=m.created_at.isoformat() if m.created_at else "",
            )
            for m in row.messages
        ],
    )


_OPENER_BY_LANG = {
    "en": (
        "Hello, I am Aria, an AI assistant from Rupeezy. I am reaching out to "
        "share details about our Authorized Person partner program, where you "
        "can earn 100 percent of the brokerage generated by your clients. Do "
        "you have two minutes to chat about how this could work for you?"
    ),
    "hi": (
        "Namaste, main Rupeezy se Aria bol rahi hoon, ek AI assistant. Main "
        "aapko hamare Authorized Person partner program ke baare mein batane "
        "ke liye call kar rahi hoon, jahan aap apne clients se generate hone "
        "wali brokerage ka 100 percent earn kar sakte hain. Kya aapke paas "
        "do minute hain?"
    ),
    "ta": (
        "Vanakkam, naan Rupeezy-in Aria, oru AI assistant. Ungal clients "
        "generate pannum brokerage-il 100 percent earn panna mudiyum engira "
        "Authorized Person partner program pathi solla call panren. Rendu "
        "nimisham pesalama?"
    ),
    "te": (
        "Namaste, nenu Rupeezy nundi Aria, oka AI assistant. Mee clients "
        "generate chese brokerage lo 100 percent earn cheyagalige Authorized "
        "Person partner program gurinchi cheppadaniki call chestunnanu. Rendu "
        "nimishalu matladacha?"
    ),
    "mr": (
        "Namaskar, mi Rupeezy kadun Aria boltey, ek AI assistant. Tumchya "
        "clients mule generate honarya brokerage che 100 percent earn karta "
        "yenarya Authorized Person partner program baddal sangayla call kelay. "
        "Don minute bolu shakto ka?"
    ),
    "gu": (
        "Namaste, hu Rupeezy taraf thi Aria bolu chhu, ek AI assistant. Tamara "
        "clients thi generate thati brokerage nu 100 percent earn kari shako "
        "eva Authorized Person partner program vishe vaat karva call karyo chhe. "
        "Be minute vaat kari shakiye?"
    ),
    "bn": (
        "Nomoshkar, ami Rupeezy theke Aria bolchi, ekjon AI assistant. Apnar "
        "clients theke generate howa brokerage-er 100 percent earn korte parben "
        "emon Authorized Person partner program niye kotha bolte call korechi. "
        "Dui minute kotha bola jabe?"
    ),
}


def _opener_for_lang(lang: str | None) -> str:
    key = (lang or "en").strip().lower().split("-")[0]
    if key in ("hinglish", "hindi"):
        key = "hi"
    return _OPENER_BY_LANG.get(key, _OPENER_BY_LANG["en"])


# ---------- routes ----------


@router.post("", response_model=CreateConversationResponse)
async def create_conversation(
    body: CreateConversationRequest | None = None,
) -> CreateConversationResponse:
    """Create a new conversation. Body is optional — pass `{lead_id}` to bind
    the conversation to a known lead so Phase 10 cross-call memory activates.
    """
    store = get_store()
    lead_id = body.lead_id if body else None
    from app.db.repo import get_lead, persist_conversation

    if lead_id:
        lead = await asyncio.to_thread(get_lead, lead_id)
        if lead is None:
            raise HTTPException(404, "Lead not found")
        if lead.dnd:
            raise HTTPException(409, "This lead opted out")
    if lead_id:
        conv = store.create_for_lead(lead_id)
        log.info("created conversation %s for lead %s", conv.conv_id, lead_id)
    else:
        conv = store.create()
        log.info("created conversation %s", conv.conv_id)
    await asyncio.to_thread(persist_conversation, conv)
    from app.db.repo import save_session_settings

    conv.settings = body.settings if body else AgentSettings()
    await asyncio.to_thread(save_session_settings, conv.conv_id, conv.settings.model_dump_json())
    return CreateConversationResponse(
        conv_id=conv.conv_id,
        started_at=conv.started_at,
        lead_id=conv.lead_id,
    )


@router.post("/{conv_id}/opener", response_model=MessageDTO)
async def conversation_opener(
    conv_id: str,
    body: OpenerRequest | None = None,
) -> MessageDTO:
    async with conversation_lock(conv_id):
        return await _conversation_opener(conv_id, body)


async def _conversation_opener(conv_id: str, body: OpenerRequest | None) -> MessageDTO:
    """Start the outbound call with Aria's opener.

    Idempotent for a brand-new conversation: if the opener was already added,
    return the existing first assistant message instead of duplicating it.
    """
    conv = get_store().get(conv_id)
    if conv is None:
        raise HTTPException(404, f"conversation {conv_id} not found")
    if conv.ended_at:
        raise HTTPException(409, f"conversation {conv_id} already ended")

    existing = next((m for m in conv.messages if m.role == "assistant"), None)
    opener = _opener_for_lang(body.lang if body else conv.settings.language)
    if conv.settings.custom:
        opener = (f"Hello, I'm {conv.settings.agent_name}, an AI assistant from "
                  f"{conv.settings.business_name}. Can we talk briefly about "
                  f"{conv.settings.program_name}?")
        if conv.settings.language in ("hinglish", "hi-IN"):
            opener = (f"Namaste, main {conv.settings.business_name} se "
                      f"{conv.settings.agent_name}, ek AI assistant hoon. "
                      f"Kya hum {conv.settings.program_name} ke baare mein baat kar sakte hain?")
    msg = existing or conv.add("assistant", opener)

    try:
        from app.db.repo import persist_conversation

        await asyncio.to_thread(persist_conversation, conv, channel=conv.channel)
    except Exception:  # noqa: BLE001
        log.exception("failed to persist opener for %s", conv.conv_id)

    return MessageDTO(role=msg.role, text=msg.text, created_at=msg.created_at)


@router.get("", response_model=list[ConversationDTO])
async def list_conversations(bucket: str | None = None, limit: int = 200) -> list[ConversationDTO]:
    """Persistent list — survives restarts. Optional bucket filter joins on handoff."""
    from app.db.repo import list_conversation_rows

    rows = await asyncio.to_thread(list_conversation_rows, bucket=bucket, limit=max(1, min(limit, 200)))
    return [_row_to_dto(r) for r in rows]


@router.get("/{conv_id}", response_model=ConversationDTO)
async def get_conversation(conv_id: str) -> ConversationDTO:
    # Hot path: in-memory store (current process).
    conv = await asyncio.to_thread(get_store().get, conv_id)
    if conv is not None:
        return _to_dto(conv)
    # Cold path: rehydrate from DB.
    from app.db.repo import get_conversation_row

    row = get_conversation_row(conv_id)
    if row is None:
        raise HTTPException(404, f"conversation {conv_id} not found")
    return _row_to_dto(row)


@router.post("/{conv_id}/turn")
async def turn(conv_id: str, body: TurnRequest):
    """SSE stream of agent reply tokens.

    Frontend connects via EventSource; consumes events of type 'token' and 'done'.
    """
    conv = get_store().get(conv_id)
    if conv is None:
        raise HTTPException(404, f"conversation {conv_id} not found")
    if conv.ended_at:
        raise HTTPException(409, f"conversation {conv_id} already ended")

    user_text = body.text.strip()
    if not user_text:
        raise HTTPException(400, "empty text")

    lang_hint = (body.lang or "").strip() or None

    # Auto-detect from this turn's text. Same logic the conversation
    # engine uses for its prompt override — exposing it here too so the
    # frontend can pick the matching TTS voice on the fly without the
    # user touching the picker.
    from app.agent.conversation import _detect_lang_from_text

    detected = _detect_lang_from_text(user_text)
    effective_lang = detected or lang_hint or conv.settings.language

    async def gen() -> AsyncIterator[dict[str, str]]:
        # Emit the resolved language FIRST so the frontend can pick the
        # right TTS voice (Edge-TTS: en-IN-Neerja vs bn-IN-Tanishaa, etc.)
        # for THIS turn's audio synthesis.
        if effective_lang:
            yield {
                "event": "lang",
                "data": json.dumps({"lang": effective_lang}),
            }
        try:
            async with conversation_lock(conv_id):
                async for chunk in stream_user_turn(conv_id, user_text, lang_hint=lang_hint):
                    yield {"event": "token", "data": json.dumps({"text": chunk})}
        except ValueError as e:
            yield {"event": "error", "data": json.dumps({"message": str(e)})}
            return
        except Exception as e:  # noqa: BLE001
            log.exception("turn failed")
            yield {"event": "error", "data": json.dumps({"message": f"agent error: {e}"})}
            return
        yield {"event": "done", "data": "{}"}

    return EventSourceResponse(gen())


@router.post("/{conv_id}/turn/audio")
async def turn_audio(conv_id: str, body: TurnRequest):
    """Retired audio path. The browser uses the supported Edge TTS route."""
    raise HTTPException(410, "Use /turn for text and /api/tts/synthesize for sentence audio.")


class EndConversationResponse(BaseModel):
    conversation: ConversationDTO
    handoff: HandoffRecord | None = None
    handoff_error: str | None = None


@router.post("/{conv_id}/end", response_model=EndConversationResponse)
async def end_conversation(conv_id: str, body: EndRequest) -> EndConversationResponse:
    async with conversation_lock(conv_id):
        return await _end_conversation(conv_id, body)


async def _end_conversation(conv_id: str, body: EndRequest) -> EndConversationResponse:
    """End the conversation AND run the post-call pipeline.

    The pipeline is best-effort — if scoring fails (rate limit, model error),
    the conversation still ends cleanly and the handoff_error field surfaces
    the reason. Frontend should render the handoff if present, fallback to
    a "scoring pending" state if not.
    """
    conv = await asyncio.to_thread(get_store().end, conv_id, ended_by=body.ended_by)
    if conv is None:
        raise HTTPException(404, f"conversation {conv_id} not found")
    from app.db.repo import get_handoff_row

    existing = await asyncio.to_thread(get_handoff_row, conv_id)
    if existing:
        return EndConversationResponse(
            conversation=_to_dto(conv),
            handoff=HandoffRecord.model_validate_json(existing.payload_json),
        )
    if conv.ended_by == "dropped":
        from app.db.repo import persist_conversation

        await asyncio.to_thread(persist_conversation, conv, channel=conv.channel)
        return EndConversationResponse(conversation=_to_dto(conv))

    # Always persist the (now-ended) conversation, even if scoring fails below.
    try:
        from app.db.repo import persist_conversation

        await asyncio.to_thread(persist_conversation, conv, channel=conv.channel)
    except Exception:  # noqa: BLE001
        log.exception("failed to persist conversation %s on /end", conv_id)

    handoff: HandoffRecord | None = None
    handoff_error: str | None = None
    if conv.messages:
        try:
            handoff = await build_handoff(conversation=conv)
            try:
                from app.db.repo import persist_handoff

                await asyncio.to_thread(persist_handoff, handoff)
            except Exception:  # noqa: BLE001
                log.exception("failed to persist handoff for %s", conv_id)
            log.info(
                "ended %s by=%s | bucket=%s confidence=%.2f next=%s",
                conv_id,
                body.ended_by,
                handoff.classification.bucket,
                handoff.classification.confidence,
                handoff.next_action.type,
            )
        except Exception as e:  # noqa: BLE001
            handoff_error = f"{type(e).__name__}: {e}"
            log.exception("handoff scoring failed for %s", conv_id)
    else:
        log.info("ended empty conversation %s — no handoff", conv_id)

    # Phase 8: fire WhatsApp follow-up. Best-effort; never fails /end.
    # DND leads are filtered inside the sender (see select_template), so we
    # only invoke it for next-actions where a message is plausibly wanted.
    if handoff and not conv.settings.custom and handoff.next_action.type in (
        "warm_transfer",
        "whatsapp_link_sent",
        "nurture_sequence",
    ):
        try:
            from app.whatsapp.sender import get_sender

            sender = get_sender()
            await sender.send(handoff)
        except Exception:  # noqa: BLE001
            log.exception("whatsapp send failed for %s", conv_id)

    return EndConversationResponse(
        conversation=_to_dto(conv),
        handoff=handoff,
        handoff_error=handoff_error,
    )


@router.get("/{conv_id}/handoff", response_model=HandoffRecord)
async def get_handoff(conv_id: str) -> HandoffRecord:
    # Cold path: rehydrate from the DB. Survives restarts.
    from app.db.repo import get_handoff_row

    row = get_handoff_row(conv_id)
    if row is None:
        raise HTTPException(404, f"no handoff for conversation {conv_id}")
    handoff = HandoffRecord.model_validate_json(row.payload_json)
    return handoff
